import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { registerFixture, registerVendorFixture } from "../../../evidence/register-migration-fixture";
import { commitRegisterMigration, loadRegisterMigration, saveRegisterMigration } from "../../registerMigrationApi";
import { loadVendorRelationships, loadVendorRelationship } from "../../vendorApi";
import { RiskRegisterMigration } from "./RiskRegisterMigration";
vi.mock("../../registerMigrationApi", async (original) => ({ ...await original<typeof import("../../registerMigrationApi")>(), loadRegisterMigration: vi.fn(), saveRegisterMigration: vi.fn(), commitRegisterMigration: vi.fn() }));
vi.mock("../../vendorApi", () => ({ loadVendorRelationships: vi.fn(), loadVendorRelationship: vi.fn() }));
beforeEach(() => {
  vi.resetAllMocks();
  vi.mocked(loadRegisterMigration).mockResolvedValue(structuredClone(registerFixture));
  vi.mocked(loadVendorRelationships).mockResolvedValue({ items: [registerVendorFixture] });
  vi.mocked(loadVendorRelationship).mockResolvedValue(registerVendorFixture);
  vi.mocked(saveRegisterMigration).mockImplementation(async (draft, selection) => ({ ...registerFixture, draft: { ...draft, version: draft.version + 1, selection } }));
  vi.mocked(commitRegisterMigration).mockImplementation(async (draft) => ({ ...draft, version: draft.version + 1, status: "IMPORTED", receipts: [{ row_id: "r1", matter_id: "m1", action_id: "a1", title: "Annual assurance certificate was not provided." }] }));
});
it("suggests exact matches, requires vendor's bank owner, and imports only after review", async () => {
  render(<RiskRegisterMigration documentID="source" />);
  await waitFor(() => expect((screen.getByLabelText("Bank owner for Hakeem") as HTMLSelectElement).value).toBe("owner"));
  await waitFor(() => expect((screen.getByLabelText("Vendor relationship for Payments") as HTMLSelectElement).value).toBe("relationship"));
  const submit = screen.getByRole("button", { name: "Import 2 findings" }) as HTMLButtonElement;
  expect(submit.disabled).toBe(true);
  fireEvent.change(screen.getByLabelText("Bank owner for Vendor"), { target: { value: "other" } });
  fireEvent.click(screen.getByLabelText("I confirm the vendor, owner and finding assignments."));
  fireEvent.click(submit);
  await screen.findByRole("heading", { name: "1 finding imported" });
  expect(saveRegisterMigration).toHaveBeenCalledTimes(1);
  expect(vi.mocked(commitRegisterMigration).mock.calls[0]?.[0].version).toBe(1);
  expect(screen.getByRole("link", { name: /Annual assurance certificate/ }).getAttribute("href")).toContain("m1");
});
it("keeps choices after an uncertain response and retries the saved import without another save", async () => {
  const draft = structuredClone(registerFixture);
  draft.draft.version = 3;
  draft.draft.selection.groups[0] = { group_id: "g1", relationship_id: "relationship", relationship_version: 4 };
  draft.draft.selection.owners.forEach((o) => { o.person_id = "owner"; });
  vi.mocked(loadRegisterMigration).mockResolvedValue(draft);
  vi.mocked(commitRegisterMigration).mockRejectedValueOnce(new Error("Connection lost. Check the import result."));
  render(<RiskRegisterMigration documentID="source" />);
  await screen.findByLabelText("I confirm the vendor, owner and finding assignments.");
  fireEvent.click(screen.getByLabelText("I confirm the vendor, owner and finding assignments."));
  fireEvent.click(screen.getByRole("button", { name: "Import 2 findings" }));
  await screen.findByRole("alert");
  fireEvent.click(screen.getByRole("button", { name: "Retry import" }));
  await screen.findByRole("heading", { name: "1 finding imported" });
  expect(saveRegisterMigration).toHaveBeenCalledTimes(1);
  expect(commitRegisterMigration).toHaveBeenCalledTimes(2);
});
it("allows an unmatched assessment to be excluded", async () => {
  const data = structuredClone(registerFixture);
  data.register.groups.push({ id: "g2", vendor: "Historical vendor", service: "Retired service", assessment_date: "2025" });
  data.draft.selection.groups.push({ group_id: "g2", relationship_id: "", relationship_version: 0 });
  data.register.rows[1]!.group_id = "g2";
  data.draft.selection.rows[1]!.include = false;
  vi.mocked(loadRegisterMigration).mockResolvedValue(data);
  render(<RiskRegisterMigration documentID="source" />);
  await waitFor(() => expect((screen.getByLabelText("Vendor relationship for Payments") as HTMLSelectElement).value).toBe("relationship"));
  fireEvent.click(screen.getByLabelText("I confirm the vendor, owner and finding assignments."));
  expect((screen.getByRole("button", { name: "Import 1 finding" }) as HTMLButtonElement).disabled).toBe(false);
});
