BEGIN;
DROP TABLE IF EXISTS continuity_events;
DROP TABLE IF EXISTS response_packages;
DROP TABLE IF EXISTS verification_results;
DROP TABLE IF EXISTS verification_contracts;
DROP TABLE IF EXISTS matter_actions;
DROP TABLE IF EXISTS matter_decisions;
DROP TABLE IF EXISTS matter_links;
DROP TABLE IF EXISTS matters;
DROP TABLE IF EXISTS program_trigger_events;
DROP TABLE IF EXISTS program_state_snapshots;
DROP TABLE IF EXISTS evidence_assessments;
DROP TABLE IF EXISTS evidence_contract_sources;
DROP TABLE IF EXISTS evidence_contracts;
DROP TABLE IF EXISTS requirement_control_links;
DROP TABLE IF EXISTS control_implementations;
DROP TABLE IF EXISTS control_objectives;
DROP TABLE IF EXISTS program_applicability;
DROP TABLE IF EXISTS program_requirements;
DROP TABLE IF EXISTS programs;
COMMIT;
