BEGIN;
DROP TABLE IF EXISTS automation_policies;
DROP TABLE IF EXISTS readiness_snapshots;
DROP TABLE IF EXISTS drift_assessments;
DROP TABLE IF EXISTS compliance_signals;
DROP TABLE IF EXISTS user_onboarding_state;
DROP TABLE IF EXISTS workflow_events;
DROP TABLE IF EXISTS workflow_tasks;
ALTER TABLE authority_grants DROP CONSTRAINT IF EXISTS authority_target_check;
ALTER TABLE authority_grants DROP COLUMN IF EXISTS role_template_id;
ALTER TABLE authority_grants DROP COLUMN IF EXISTS position_id;
ALTER TABLE authority_grants ALTER COLUMN principal_id SET NOT NULL;
ALTER TABLE responsibility_assignments DROP CONSTRAINT IF EXISTS responsibility_target_check;
ALTER TABLE responsibility_assignments DROP COLUMN IF EXISTS resolution_strategy;
ALTER TABLE responsibility_assignments DROP COLUMN IF EXISTS decision_type;
ALTER TABLE responsibility_assignments DROP COLUMN IF EXISTS role_template_id;
ALTER TABLE responsibility_assignments DROP COLUMN IF EXISTS position_id;
ALTER TABLE responsibility_assignments ALTER COLUMN principal_id SET NOT NULL;
DROP TABLE IF EXISTS routing_policy_versions;
DROP TABLE IF EXISTS routing_policies;
DROP TABLE IF EXISTS delegations;
DROP TABLE IF EXISTS position_role_bindings;
DROP TABLE IF EXISTS role_templates;
DROP TABLE IF EXISTS org_positions;
COMMIT;
