package bankverticals

func referenceRequirementSpecs() []requirementSpec {
	return []requirementSpec{
		{code: "PROCESSING-ACCOUNTABILITY", title: "Keep personal-data processing accountable", statement: "The bank must process personal data fairly, lawfully and accountably for defined purposes.", anchor: "NDP Act 2023, section 24", objectiveCode: "PROCESSING-RECORDS", objectiveName: "Current processing records", outcome: "Every active processing activity has a current purpose, lawful basis, owner, data set, recipient and retention record.", implementationName: "Quarterly processing-owner review", implementationType: "OWNER_REVIEW", implementationDetail: "Processing owners confirm new, changed and retired processing activities each quarter."},
		{code: "DATA-SUBJECT-RIGHTS", title: "Respond to data rights requests", statement: "The bank must receive, assess and complete valid data-subject requests through a controlled process.", anchor: "NDP Act 2023, data-subject rights provisions", objectiveCode: "RIGHTS-TIMELINESS", objectiveName: "Timely rights handling", outcome: "Each request has identity checks, scope, response decision, completion date and supporting evidence.", implementationName: "Data rights case workflow", implementationType: "CASE_MANAGEMENT", implementationDetail: "The Privacy Office monitors open requests, ageing and approved extensions each business day."},
		{code: "PRIVACY-INCIDENTS", title: "Assess personal-data incidents", statement: "The bank must identify, assess, contain and document personal-data incidents and make required notifications.", anchor: "NDP Act 2023, personal-data breach provisions", objectiveCode: "INCIDENT-ASSESSMENT", objectiveName: "Complete privacy incident assessment", outcome: "Every suspected personal-data incident has severity, affected data, containment, notification decision and closure evidence.", implementationName: "Privacy incident assessment", implementationType: "INCIDENT_RESPONSE", implementationDetail: "Cybersecurity and the Privacy Office jointly assess incidents with possible personal-data impact."},
		{code: "DPIA-HIGH-RISK", title: "Review high-risk processing before release", statement: "The bank must assess high-risk processing and record privacy safeguards before the change goes live.", anchor: "NDP Act 2023 and GAID 2025 DPIA requirements", objectiveCode: "DPIA-GATE", objectiveName: "Privacy review before release", outcome: "High-risk product and technology changes have an approved privacy impact assessment before production release.", implementationName: "High-risk change privacy gate", implementationType: "CHANGE_GATE", implementationDetail: "The change portfolio routes high-risk processing to the Privacy Office before release approval."},
		{code: "CAR-ANNUAL", title: "Prepare the annual compliance audit return", statement: "The bank must maintain the records and independent review needed for its annual Compliance Audit Return.", anchor: "GAID 2025, Articles 10.7 and 10.8; filing before 31 March", objectiveCode: "CAR-READINESS", objectiveName: "Annual audit return ready for filing", outcome: "The DPCO receives a complete, approved and traceable evidence pack before the filing deadline.", implementationName: "Annual CAR readiness review", implementationType: "ANNUAL_CERTIFICATION", implementationDetail: "The Privacy Office and licensed DPCO review the evidence pack, unresolved findings and management approval before filing."},
	}
}
