import type { IndicatorPopulationPage } from "./indicatorTypes";
import type { MonitoringResult } from "./monitoringTypes";
import type { RiskIndicatorDetail } from "./riskTypes";

export const sampleMobileSuccessIndicator: RiskIndicatorDetail = {
  link: {
    id: "sample-indicator-link",
    risk_id: "sample-risk-mobile",
    risk_version: 3,
    program_id: "sample-channel-program",
    monitoring_check_id: "sample-mobile-success",
    monitoring_check_version: 4,
    kind: "KRI",
    measurement: "MONITORING_RISK_SCORE",
    created_at: "2026-10-05T08:00:00Z",
  },
  program_id: "sample-channel-program",
  program_name: "Digital channels",
  check_id: "sample-mobile-success",
  check_code: "MOBILE-SUCCESS",
  check_name: "Mobile transaction success rate",
  claim: "Mobile transaction success remains at or above the approved operating limit.",
  check_status: "ACTIVE",
  check_version: 4,
  input_kind: "SOURCE",
  owner_display_name: "Channel Operations",
  reviewer_display_name: "Technology Risk",
  measurement: "MONITORING_RISK_SCORE",
  unit: "RISK_POINTS",
  denominator: 100,
  native_measurement: {
    field: "success_rate",
    label: "Success rate",
    unit: "PERCENT",
    precision: 2,
    value: "98.70",
    limits: [{ operator: "GREATER_OR_EQUAL", expected: "99.50" }],
    condition: "BREACHED",
    reporting_period_start: "2026-09-01T00:00:00Z",
    reporting_period_end: "2026-09-30T23:59:59Z",
  },
  movement: {
    direction: "DOWN",
    delta: "-0.40",
    previous_evaluated_at: "2026-09-05T10:00:00Z",
  },
  state: "BREACH",
  reason: "Latest native measurement is outside its approved limit.",
  score: 100,
  band: "CRITICAL",
  coverage: 1,
  minimum_coverage: 0.95,
  freshness_minutes: 525600,
  result_id: "sample-result-3",
  evaluated_at: "2026-10-05T10:00:00Z",
  intervention: {
    matter_id: "sample-matter",
    reference: "MAT-2041",
    status: "ASSESSMENT",
    priority: 3,
    created_at: "2026-10-05T10:05:00Z",
  },
};

export const sampleATMFailureIndicator: RiskIndicatorDetail = {
  link: {
    id: "sample-atm-indicator-link",
    risk_id: "sample-risk-atm",
    risk_version: 2,
    program_id: "sample-channel-program",
    monitoring_check_id: "sample-atm-failures",
    monitoring_check_version: 2,
    kind: "KRI",
    measurement: "MONITORING_RISK_SCORE",
    created_at: "2026-10-04T08:00:00Z",
  },
  program_id: "sample-channel-program",
  program_name: "Digital channels",
  check_id: "sample-atm-failures",
  check_code: "ATM-FAILURES",
  check_name: "Failed ATM transactions",
  claim: "Failed ATM transactions remain within the approved monthly limit.",
  check_status: "ACTIVE",
  check_version: 2,
  input_kind: "SOURCE",
  owner_display_name: "Payments Operations",
  reviewer_display_name: "Technology Risk",
  measurement: "MONITORING_RISK_SCORE",
  unit: "RISK_POINTS",
  denominator: 100,
  native_measurement: {
    field: "failed_transactions",
    label: "Failed transactions",
    unit: "COUNT",
    precision: 0,
    value: "84",
    limits: [{ operator: "LESS_OR_EQUAL", expected: "100" }],
    condition: "WITHIN",
    reporting_period_start: "2026-09-01T00:00:00Z",
    reporting_period_end: "2026-09-30T23:59:59Z",
  },
  movement: {
    direction: "DOWN",
    delta: "-18",
    previous_evaluated_at: "2026-09-04T10:00:00Z",
  },
  state: "NORMAL",
  reason: "Latest native measurement is within its approved limit.",
  score: 0,
  band: "LOW",
  coverage: 1,
  minimum_coverage: 0.95,
  freshness_minutes: 525600,
  result_id: "sample-atm-result-2",
  evaluated_at: "2026-10-04T10:00:00Z",
};

export const sampleIndicatorHistory: MonitoringResult[] = [
  {
    id: "sample-result-3",
    monitoring_check_id: sampleMobileSuccessIndicator.check_id,
    monitoring_check_version: sampleMobileSuccessIndicator.check_version,
    evaluated_at: "2026-10-05T10:00:00Z",
    evaluation: {
      score: 100,
      band: "CRITICAL",
      coverage: 1,
      measurement: sampleMobileSuccessIndicator.native_measurement,
    },
  },
  {
    id: "sample-result-2",
    monitoring_check_id: sampleMobileSuccessIndicator.check_id,
    monitoring_check_version: sampleMobileSuccessIndicator.check_version,
    evaluated_at: "2026-09-05T10:00:00Z",
    evaluation: {
      score: 100,
      band: "CRITICAL",
      coverage: 1,
      measurement: {
        ...sampleMobileSuccessIndicator.native_measurement!,
        value: "99.10",
        reporting_period_start: "2026-08-01T00:00:00Z",
        reporting_period_end: "2026-08-31T23:59:59Z",
      },
    },
  },
];

export const sampleATMIndicatorHistory: MonitoringResult[] = [
  {
    id: "sample-atm-result-2",
    monitoring_check_id: sampleATMFailureIndicator.check_id,
    monitoring_check_version: sampleATMFailureIndicator.check_version,
    evaluated_at: "2026-10-04T10:00:00Z",
    evaluation: {
      score: 0,
      band: "LOW",
      coverage: 1,
      measurement: sampleATMFailureIndicator.native_measurement,
    },
  },
  {
    id: "sample-atm-result-1",
    monitoring_check_id: sampleATMFailureIndicator.check_id,
    monitoring_check_version: sampleATMFailureIndicator.check_version,
    evaluated_at: "2026-09-04T10:00:00Z",
    evaluation: {
      score: 100,
      band: "CRITICAL",
      coverage: 1,
      measurement: {
        ...sampleATMFailureIndicator.native_measurement!,
        value: "102",
        condition: "BREACHED",
        reporting_period_start: "2026-08-01T00:00:00Z",
        reporting_period_end: "2026-08-31T23:59:59Z",
      },
    },
  },
];

export const sampleIndicatorInsightsPage: IndicatorPopulationPage = {
  complete: true,
  items: [
    {
      indicator: sampleMobileSuccessIndicator,
      risk_count: 1,
      risks: [{
        id: "sample-risk-mobile",
        code: "TECH-CHANNEL-01",
        name: "Mobile channel availability",
        organization_scope_id: "scope-head-office",
        status: "ACTIVE",
      }],
    },
    {
      indicator: sampleATMFailureIndicator,
      risk_count: 1,
      risks: [{
        id: "sample-risk-atm",
        code: "TECH-CHANNEL-02",
        name: "ATM transaction failures",
        organization_scope_id: "scope-branch-cac",
        status: "ACTIVE",
      }],
    },
  ],
};
