import "./staticDemoBootstrap";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import { ExternalCaptureApp } from "./components/ExternalCaptureApp";
import { DisplayPreferencesRoot } from "./components/DisplayPreferences";
import "./styles.css";
import "./evidence.css";
import "./continuity.css";
import "./journeys.css";
import "./document-import.css";
import "./interventions.css";
import "./automation-policies.css";
import "./product-finish.css";
import "./ui-preferences.css";
import "./visual-review-fixes.css";
import "./capture-inputs.css";

const root = document.getElementById("root");
if (!root) throw new Error("Application root is missing");
const invitationToken = new URLSearchParams(window.location.search).get("capture_invite");
const application = invitationToken ? <ExternalCaptureApp invitationToken={invitationToken}/> : <App/>;
createRoot(root).render(<StrictMode><DisplayPreferencesRoot>{application}</DisplayPreferencesRoot></StrictMode>);
