(function installStaticDemoWorkflowRuntime(global) {
  const accounts = [
    { label: "Chief Risk Officer", username: "cro@demo.clearsight", password: "demo", actor: { id: "role-cro", name: "Chief Risk Officer", kind: "PERSON", role_codes: ["CRO", "EXECUTIVE"] } },
    { label: "Data Protection Officer", username: "dpo@demo.clearsight", password: "demo", actor: { id: "role-dpo", name: "Data Protection Officer", kind: "PERSON", role_codes: ["DPO", "PROGRAM_OWNER"] } },
    { label: "Data Protection Compliance Officer", username: "dpco@demo.clearsight", password: "demo", actor: { id: "role-dpco", name: "Data Protection Compliance Officer", kind: "PERSON", role_codes: ["DPCO", "REVIEWER"] } },
    { label: "Privacy Control Owner", username: "control@demo.clearsight", password: "demo", actor: { id: "role-privacy-control", name: "Privacy Control Owner", kind: "PERSON", role_codes: ["CONTROL_OWNER", "PERFORMER"] } },
  ];

  const transitions = {
    matter: { DRAFT: ["INITIAL_REVIEW", "CANCELLED"], INITIAL_REVIEW: ["ASSESSMENT", "CANCELLED"], ASSESSMENT: ["DECISION_REQUIRED", "ACTION_IN_PROGRESS", "RESPONSE_PREPARATION", "VERIFICATION", "CANCELLED"], DECISION_REQUIRED: ["ACTION_IN_PROGRESS", "RESPONSE_PREPARATION", "VERIFICATION", "CANCELLED"], ACTION_IN_PROGRESS: ["VERIFICATION", "RESPONSE_PREPARATION", "CANCELLED"], RESPONSE_PREPARATION: ["VERIFICATION", "CANCELLED"], VERIFICATION: ["CLOSED", "DECISION_REQUIRED", "ACTION_IN_PROGRESS", "RESPONSE_PREPARATION", "CANCELLED"], CLOSED: ["ASSESSMENT"] },
    action: { PLANNED: ["IN_PROGRESS", "BLOCKED", "CANCELLED"], IN_PROGRESS: ["IMPLEMENTED", "BLOCKED", "CANCELLED"], BLOCKED: ["IN_PROGRESS", "CANCELLED"] },
    response: { DRAFT: ["IN_REVIEW", "WITHDRAWN"], IN_REVIEW: ["APPROVED", "REJECTED", "DRAFT", "WITHDRAWN"], APPROVED: ["TRANSMITTED", "WITHDRAWN"], TRANSMITTED: ["ACKNOWLEDGED"], REJECTED: ["DRAFT"] },
    safeguard: { PLANNED: ["IN_PROGRESS", "RETIRED"], IN_PROGRESS: ["IMPLEMENTED", "INACTIVE", "RETIRED"], IMPLEMENTED: ["INACTIVE", "RETIRED"], INACTIVE: ["IN_PROGRESS", "RETIRED"] },
    program: { DRAFT: ["ACTIVE", "RETIRED"], ACTIVE: ["PAUSED", "RETIRED"], PAUSED: ["ACTIVE", "RETIRED"] },
    monitoring: { DRAFT: ["PENDING_APPROVAL"], PENDING_APPROVAL: ["ACTIVE", "REJECTED"], ACTIVE: ["PAUSED", "RETIRED"], PAUSED: ["ACTIVE", "RETIRED"] },
    decision: { PROPOSED: ["IN_REVIEW", "CHALLENGED", "APPROVED", "CONDITIONALLY_APPROVED", "REJECTED", "RETURNED", "SUPERSEDED"], IN_REVIEW: ["CHALLENGED", "APPROVED", "CONDITIONALLY_APPROVED", "REJECTED", "RETURNED", "SUPERSEDED"], CHALLENGED: ["APPROVED", "CONDITIONALLY_APPROVED", "REJECTED", "RETURNED", "SUPERSEDED"], RETURNED: ["PROPOSED", "SUPERSEDED"], REJECTED: ["PROPOSED", "SUPERSEDED"], APPROVED: ["PROPOSED", "SUPERSEDED", "EXPIRED"], CONDITIONALLY_APPROVED: ["PROPOSED", "SUPERSEDED", "EXPIRED"], EXPIRED: ["PROPOSED", "SUPERSEDED"], SUPERSEDED: ["PROPOSED"] },
  };
  const targets = (kind, status) => transitions[kind][status] || [];
  const pick = (value, keys) => Object.fromEntries(keys.filter((key) => value[key] !== undefined).map((key) => [key, value[key]]));
  const outcomeFields = (input) => pick(input, ["action_id", "expected_outcome", "baseline", "scope", "measurement_source_id", "threshold", "observation_period_minutes", "failure_response"]);
  const principal = (id) => {
    const account = accounts.find((item) => item.actor.id === id);
    return account ? { id: account.actor.id, display_name: account.actor.name, kind: "POSITION", role: account.actor.role_codes[0] } : { id, display_name: "Recorded responsible person", kind: "PERSON", role: "Recorded assignment" };
  };
  const groupTargets = (values, resolve) => {
    const groups = new Map();
    for (const target of values) groups.set(resolve(target), [...(groups.get(resolve(target)) || []), target]);
    return groups;
  };
  const decisionResponsibility = (target) => target === "PROPOSED" ? "PROPOSER" : ["IN_REVIEW", "RETURNED"].includes(target) ? "REVIEWER" : target === "CHALLENGED" ? "INDEPENDENT_CHALLENGER" : "AUTHORIZER";
  const decisionPrincipal = (responsibility) => responsibility === "AUTHORIZER" ? principal("role-cro") : responsibility === "INDEPENDENT_CHALLENGER" ? principal("role-privacy-control") : responsibility === "PROPOSER" ? principal("role-dpo") : principal("role-dpco");
  const responsePrincipal = (responsibility) => responsibility === "SIGNATORY" ? principal("role-cro") : ["PROPOSER", "TRANSMITTER"].includes(responsibility) ? principal("role-dpo") : principal("role-dpco");

  function authRequest({ pathname, method, input, ErrorType }) {
    if (pathname === "/api/v1/session/status") return { handled: true, body: { authenticated: true, demo_login_available: true } };
    if (pathname === "/api/v1/demo/accounts") return { handled: true, body: { accounts: accounts.map(({ actor, ...account }) => ({ ...account, role_codes: actor.role_codes })) } };
    if (pathname === "/api/v1/demo/login" && method === "POST") { const account = accounts.find((item) => item.username === input.username); if (!account) throw new ErrorType(401, "invalid_credentials", "Choose one of the available stakeholder demo accounts."); return { handled: true, actor: account.actor, body: { account: { label: account.label, username: account.username, password: account.password, role_codes: account.actor.role_codes } } }; }
    if (pathname === "/api/v1/demo/logout" && method === "POST") return { handled: true, body: {} };
    return { handled: false };
  }

  function changeMatterContext(matter, input) {
    const label = String(input.label || ""); const key = String(input.key || label).trim();
    if (["ADD_FACT", "CORRECT_FACT", "RESOLVE_MISSING"].includes(input.kind)) matter.known_facts[key] = input.value;
    if (input.kind === "RETIRE_FACT") delete matter.known_facts[key];
    if (input.kind === "ADD_MISSING") matter.missing_facts.push(label);
    if (input.kind === "RESOLVE_MISSING") matter.missing_facts = matter.missing_facts.filter((item) => typeof item === "string" ? item !== label : item?.label !== label && item?.key !== key);
    if (input.kind === "ADD_CONTRADICTION") matter.contradictions.push({ key, label, value: input.value });
    if (input.kind === "RESOLVE_CONTRADICTION") matter.contradictions = matter.contradictions.filter((item) => item?.key !== key && item?.label !== label);
  }

  function finishMatterMutation({ matter, detail, summary, now }) {
    matter.version += 1; matter.updated_at = now;
    const openActions = detail.actions.filter((item) => !["IMPLEMENTED", "CANCELLED"].includes(item.status));
    const activeChecks = detail.verification_contracts.filter((item) => item.status === "ACTIVE");
    const latestResult = (id) => [...detail.verification_results].reverse().find((item) => item.contract_id === id);
    const reasons = [];
    if (openActions.length) reasons.push(`${openActions.length} action(s) are still open.`);
    const incompleteChecks = activeChecks.filter((item) => latestResult(item.id)?.result !== "PASS");
    if (incompleteChecks.length) reasons.push(`${incompleteChecks.length} outcome check(s) have not passed.`);
    if (matter.type === "REGULATORY_CHANGE") {
      const current = new Map(); for (const item of detail.decisions) current.set(item.type, item);
      const states = [...current.values()].map((item) => item.status);
      if (!states.length || states.some((status) => !["APPROVED", "CONDITIONALLY_APPROVED"].includes(status))) reasons.push("The current regulatory position is unresolved.");
      if (!activeChecks.length) reasons.push("No outcome check has been defined for the required change.");
      if (!detail.actions.some((item) => item.status === "IMPLEMENTED")) reasons.push("No implemented change has been recorded.");
    }
    detail.closure = { ready: reasons.length === 0, reasons };
    detail.status_label = ({ DRAFT: "Draft", INITIAL_REVIEW: "Initial review", ASSESSMENT: "Assessment", DECISION_REQUIRED: "Decision needed", ACTION_IN_PROGRESS: "Work in progress", RESPONSE_PREPARATION: "Response preparation", VERIFICATION: "Outcome verification", CLOSED: "Closed", CANCELLED: "Cancelled" })[matter.status] || matter.status;
    detail.next_action = matter.status === "CLOSED" ? "Review the completed record" : openActions[0]?.title || (incompleteChecks.length ? "Record the independent outcome" : detail.closure.ready ? "Close the issue with a rationale" : "Review the remaining closure conditions");
    Object.assign(summary, { matter, status_label: detail.status_label, next_action: detail.next_action, open_action_count: openActions.length, outcome_check_count: activeChecks.length });
  }

  function matterOperations({ matter, detail, currentActor, now }) {
    const owner = principal(matter.owner_principal_id), reviewer = principal("role-dpco"), authorizer = principal("role-cro"), performer = principal("role-privacy-control"), candidates = [owner, performer, reviewer];
    const operation = (command, label, assigned, responsibility, subresource_id, allowed_targets, includeCandidates = false) => ({ command, label, responsibility, subresource_id, allowed_targets, candidates: includeCandidates ? candidates : undefined, assigned_to: assigned, can_act: currentActor.id === assigned.id, reason: currentActor.id === assigned.id ? "You hold the current responsibility for this issue and can complete this action." : `Assigned to ${assigned.display_name} for the current issue state.` });
    const operations = [operation("matter.details.update", "Edit issue details", owner, "ACCOUNTABLE_OWNER"), operation("matter.context.change", "Update facts and missing information", owner, "ACCOUNTABLE_OWNER"), operation("matter.assign", "Change issue owner", owner, "ACCOUNTABLE_OWNER", undefined, undefined, true), operation("matter.link", "Link this issue", owner, "ACCOUNTABLE_OWNER"), operation("matter.action.add", "Add an action", owner, "ACCOUNTABLE_OWNER", undefined, undefined, true), operation("matter.outcome.define", "Define an outcome check", reviewer, "REVIEWER", undefined, undefined, true)];
    if (matter.status === "DECISION_REQUIRED" && detail.decisions.length === 0) operations.push(operation("matter.decision.record", "Propose decision", owner, "PROPOSER"));
    if (matter.type === "AUTHORITY_REQUEST" || matter.status === "RESPONSE_PREPARATION") operations.push(operation("matter.response.add", "Prepare response", owner, "PROPOSER"));
    const matterTargets = targets("matter", matter.status), ordinary = matterTargets.filter((target) => !["DECISION_REQUIRED", "CLOSED", "CANCELLED"].includes(target)), governed = matterTargets.filter((target) => ["DECISION_REQUIRED", "CLOSED", "CANCELLED"].includes(target));
    if (ordinary.length) operations.push(operation("matter.transition", "Change issue status", owner, "ACCOUNTABLE_OWNER", undefined, ordinary));
    if (governed.length) operations.push(operation("matter.transition", "Authorize issue status", authorizer, "AUTHORIZER", undefined, governed));
    for (const link of detail.links) operations.push(operation("matter.unlink", "Remove linked Program", owner, "ACCOUNTABLE_OWNER", link.id));
    for (const action of detail.actions) if (!["IMPLEMENTED", "CANCELLED"].includes(action.status)) { const actionOwner = principal(action.owner_principal_id || performer.id); operations.push(operation("matter.action.update", "Edit action", owner, "ACCOUNTABLE_OWNER", action.id), operation("matter.action.assign", "Change action owner", owner, "ACCOUNTABLE_OWNER", action.id, undefined, true), operation("matter.action.transition", "Update action status", actionOwner, "PERFORMER", action.id, targets("action", action.status))); }
    for (const contract of detail.verification_contracts) if (contract.status === "ACTIVE") { const assigned = principal(contract.authority_principal_id || reviewer.id); operations.push(operation("matter.outcome.supersede", "Replace outcome check", assigned, "REVIEWER", contract.id, undefined, true), operation("matter.outcome.retire", "End outcome check", assigned, "REVIEWER", contract.id), operation("matter.outcome.record", "Record outcome", assigned, "REVIEWER", contract.id, ["PASS", "FAIL", "INCONCLUSIVE"])); }
    const currentDecisions = new Map(); for (const item of detail.decisions) currentDecisions.set(item.type, item);
    for (const decision of currentDecisions.values()) for (const [responsibility, allowed] of groupTargets(targets("decision", decision.status), decisionResponsibility)) operations.push(operation("matter.decision.record", `Continue ${decision.type} decision`, decisionPrincipal(responsibility), responsibility, decision.id, allowed));
    for (const response of detail.response_packages) {
      const resolve = (target) => target === "APPROVED" ? "SIGNATORY" : target === "TRANSMITTED" ? "TRANSMITTER" : target === "ACKNOWLEDGED" ? "ACKNOWLEDGEMENT_RECORDER" : target === "WITHDRAWN" ? response.status === "APPROVED" ? "SIGNATORY" : "PROPOSER" : target === "DRAFT" && response.status === "REJECTED" ? "PROPOSER" : "REVIEWER";
      for (const [responsibility, allowed] of groupTargets(targets("response", response.status), resolve)) operations.push(operation("matter.response.transition", "Update response status", responsePrincipal(responsibility), responsibility, response.id, allowed));
    }
    return { matter_id: matter.id, matter_version: matter.version, authority_available: true, responsibility_labels_complete: true, responsible_parties: [{ scope: "RECORD", responsibility: "ACCOUNTABLE_OWNER", display_name: owner.display_name, kind: owner.kind }, ...detail.actions.map((item) => ({ scope: "ACTION", subresource_id: item.id, responsibility: "PERFORMER", display_name: principal(item.owner_principal_id || performer.id).display_name, kind: "POSITION" })), ...detail.verification_contracts.map((item) => ({ scope: "OUTCOME_CHECK", subresource_id: item.id, responsibility: "REVIEWER", display_name: principal(item.authority_principal_id || reviewer.id).display_name, kind: "POSITION" }))], operations, generated_at: now };
  }

  function matterMutationRequest({ pathname, method, input, matterID, matter, detail, summary, history, actor, ErrorType, now }) {
    if (method !== "POST") return { handled: false };
    const fail = (status, code, message) => { throw new ErrorType(status, code, message); };
    if (pathname.startsWith(`/api/v1/matters/${matterID}/`) && input.expected_version !== matter.version) fail(409, "version_conflict", "The issue changed before this update was recorded.");
    const finish = () => { finishMatterMutation({ matter, detail, summary, now }); return { handled: true, body: detail }; };
    if (pathname === `/api/v1/matters/${matterID}/details`) { Object.assign(matter, pick(input, ["title", "summary", "priority", "due_at", "scope"])); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/context-changes`) { changeMatterContext(matter, input); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/assignment`) { matter.owner_principal_id = input.owner_principal_id; return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/transition`) { if (!targets("matter", matter.status).includes(input.to) || input.to === "CLOSED" && !detail.closure.ready) fail(409, "transition_invalid", `The issue cannot move from ${matter.status} to ${input.to}.`); matter.status = input.to; matter.closed_at = input.to === "CLOSED" ? now : undefined; matter.closure_reason = input.to === "CLOSED" ? input.rationale : undefined; return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/links`) { detail.links.push({ id: `link-${detail.links.length + 1}`, program_id: input.program_id, requirement_id: input.requirement_id, control_id: input.control_id, relationship: input.relationship }); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/decisions`) { const current = [...detail.decisions].reverse().find((item) => item.type === input.type), allowed = current ? targets("decision", current.status) : ["PROPOSED", "APPROVED", "CONDITIONALLY_APPROVED", "REJECTED"]; if (!allowed.includes(input.status)) fail(409, "transition_invalid", `The decision cannot move from ${current?.status || "not recorded"} to ${input.status}.`); detail.decisions.push({ id: `decision-${detail.decisions.length + 1}`, ...pick(input, ["type", "status", "options", "selected_option", "rationale", "conditions", "expires_at"]), decided_at: now, actor_principal_id: actor.id }); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/actions`) { detail.actions.push({ id: `action-${detail.actions.length + 1}`, ...pick(input, ["title", "description", "owner_principal_id", "due_at"]), status: "PLANNED", version: 1, created_at: now, updated_at: now }); return finish(); }
    if (/\/api\/v1\/matters\/[^/]+\/actions\/[^/]+(\/assignment|\/transition)?$/.test(pathname)) { const parts = pathname.split("/"), command = parts.at(-1), id = decodeURIComponent(["assignment", "transition"].includes(command) ? parts.at(-2) || "" : command || ""), action = detail.actions.find((item) => item.id === id); if (!action) fail(404, "action_not_found", "The selected action is no longer available."); if (command === "assignment") action.owner_principal_id = input.owner_principal_id; else if (command === "transition") { if (!targets("action", action.status).includes(input.to)) fail(409, "transition_invalid", `The action cannot move from ${action.status} to ${input.to}.`); action.status = input.to; if (input.to === "IMPLEMENTED") action.implemented_at = now; } else Object.assign(action, pick(input, ["title", "description", "due_at"])); action.version = (action.version || 1) + 1; action.updated_at = now; return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/verification-contracts`) { detail.verification_contracts.push({ id: `verify-${detail.verification_contracts.length + 1}`, ...outcomeFields(input), authority_principal_id: input.reviewer_candidate_id, status: "ACTIVE", version: 1 }); return finish(); }
    if (/\/api\/v1\/matters\/[^/]+\/verification-contracts\/[^/]+\/(supersede|retire)$/.test(pathname)) { const parts = pathname.split("/"), command = parts.at(-1), id = decodeURIComponent(parts.at(-2) || ""), prior = detail.verification_contracts.find((item) => item.id === id); if (!prior) fail(404, "verification_contract_not_found", "The selected outcome check is no longer available."); prior.status = "RETIRED"; prior.version = (prior.version || 1) + 1; if (command === "supersede") detail.verification_contracts.push({ id: `${id}-replacement-${prior.version}`, supersedes_contract_id: id, ...outcomeFields(input), authority_principal_id: input.reviewer_candidate_id, status: "ACTIVE", version: 1 }); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/verification-results`) { detail.verification_results.push({ id: `result-${detail.verification_results.length + 1}`, ...pick(input, ["contract_id", "result", "observations", "evidence_references", "rationale", "observed_at"]), reviewer_principal_id: actor.id }); return finish(); }
    if (pathname === `/api/v1/matters/${matterID}/responses`) { const response = { id: `response-${detail.response_packages.length + 1}`, ...pick(input, ["purpose", "audience", "manifest"]), status: "DRAFT" }; detail.response_packages.push(response); history[response.id] = [{ status: "DRAFT", occurred_at: now, actor_label: actor.name, matter_version: matter.version + 1 }]; return finish(); }
    if (/\/api\/v1\/matters\/[^/]+\/responses\/[^/]+\/transition$/.test(pathname)) { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), response = detail.response_packages.find((item) => item.id === id); if (!response) fail(404, "response_not_found", "The selected response is no longer available."); if (!targets("response", response.status).includes(input.to)) fail(409, "transition_invalid", `The response cannot move from ${response.status} to ${input.to}.`); response.status = input.to; history[id] ||= []; history[id].push({ status: input.to, occurred_at: now, actor_label: actor.name, matter_version: matter.version + 1 }); return finish(); }
    if (/\/api\/v1\/matters\/[^/]+\/links\/[^/]+\/retirement$/.test(pathname)) { const id = decodeURIComponent(pathname.split("/").at(-2) || ""); detail.links = detail.links.filter((value) => value.id !== id); return finish(); }
    return { handled: false };
  }

  function programOperations({ program, detail, base, forms, checks, currentActor, now }) {
    const owner = principal(program.owner_principal_id), authority = principal(program.authority_principal_id), reviewer = principal("role-dpco"), performer = principal("role-privacy-control");
    const ownerCommands = new Set(["program.details.update", "program.assign", "program.requirement.add", "program.safeguard.define", "program.evidence.define", "program.requirement.supersede"]), authorityCommands = new Set(["program.approval-authority.assign", "program.applicability.decide", "program.review.accept", "program.transition"]);
    const operations = (base.operations || []).map((item) => { const assigned = ownerCommands.has(item.command) ? owner : authorityCommands.has(item.command) ? authority : item.assigned_to || reviewer; return { ...item, assigned_to: assigned, allowed_targets: item.command === "program.transition" ? targets("program", program.status) : item.allowed_targets, can_act: assigned.id === currentActor.id, reason: assigned.id === currentActor.id ? "You hold the current responsibility for this Program and can complete this action." : `Assigned to ${assigned.display_name} for the current Program state.` }; });
    const add = (command, subresource_id, label, assigned, responsibility, allowed_targets, candidates) => operations.push({ command, subresource_id, label, responsibility, can_act: assigned.id === currentActor.id, assigned_to: assigned, candidates, allowed_targets, reason: assigned.id === currentActor.id ? "You hold the current responsibility for this Program and can complete this action." : `Assigned to ${assigned.display_name} for this Program resource.` });
    for (const item of detail.control_implementations) if (item.status !== "RETIRED") { add("program.safeguard.update", item.id, `Edit ${item.name}`, owner, "ACCOUNTABLE_OWNER"); add("program.safeguard.assign", item.id, `Change the owner of ${item.name}`, owner, "ACCOUNTABLE_OWNER", undefined, [principal("role-privacy-control"), principal("role-dpo")]); const allowed = targets("safeguard", item.status); if (allowed.length) add("program.safeguard.transition", item.id, `Change ${item.name} status`, principal(item.owner_principal_id), "PERFORMER", allowed); }
    const fixtureAssessments = new Set((base.operations || []).filter((item) => item.command === "program.evidence.assess").map((item) => item.subresource_id));
    for (const item of detail.evidence_contracts) if (item.status !== "RETIRED") { add("program.evidence.revise", item.id, `Edit ${item.name}`, owner, "ACCOUNTABLE_OWNER"); const allowed = item.status === "ACTIVE" ? ["RETIRED"] : item.status === "DRAFT" ? item.configured_by === currentActor.id ? ["RETIRED"] : ["ACTIVE", "RETIRED"] : []; if (allowed.length) add("program.evidence.transition", item.id, `Review ${item.name} status`, reviewer, "REVIEWER", allowed); if (item.status === "ACTIVE" && !fixtureAssessments.has(item.id)) add("program.evidence.assess", item.id, `Record a result for ${item.name}`, reviewer, "REVIEWER"); }
    add("program.monitoring.form.define", "", "Create collection form", owner, "ACCOUNTABLE_OWNER"); add("program.monitoring.define", "", "Create monitoring check", owner, "ACCOUNTABLE_OWNER");
    for (const form of forms) { const allowed = targets("monitoring", form.status), assigned = form.status === "PENDING_APPROVAL" ? reviewer : owner; add("program.monitoring.form.transition", form.id, `Change ${form.name} status`, assigned, form.status === "PENDING_APPROVAL" ? "REVIEWER" : "ACCOUNTABLE_OWNER", allowed); if (form.status === "ACTIVE") add("program.monitoring.collect", form.id, `Collect ${form.name}`, owner, "ACCOUNTABLE_OWNER"); }
    for (const check of checks) { const allowed = targets("monitoring", check.status), assigned = check.status === "PENDING_APPROVAL" ? reviewer : owner; add("program.monitoring.transition", check.id, `Change ${check.name} status`, assigned, check.status === "PENDING_APPROVAL" ? "REVIEWER" : "ACCOUNTABLE_OWNER", allowed); if (check.status === "ACTIVE" && check.input_kind === "SOURCE") add("program.monitoring.evaluate", check.id, `Check ${check.name} now`, performer, "PERFORMER"); if (check.status === "ACTIVE" && check.failure_action === "RECOMMEND_MATTER") add("program.monitoring.issue.create", check.id, `Create linked issue for ${check.name}`, reviewer, "REVIEWER"); }
    if (program.id !== "program-ndpa") for (const item of operations) if (item.command === "program.review.accept") { item.can_act = false; item.reason = "A calculated Program status must be available before this review can be accepted."; }
    return { ...base, program_version: program.version, operations, generated_at: now };
  }

  function programResourceRequest({ pathname, method, input, program, detail, summary, actor, ErrorType, now }) {
    if (method !== "POST") return { handled: false };
    const fail = (status, code, message) => { throw new ErrorType(status, code, message); };
    const finish = () => { program.version += 1; program.updated_at = now; summary.program_version = program.version; summary.projection_stale = true; return { handled: true, body: detail }; };
    if (/\/api\/v1\/programs\/[^/]+\/control-implementations\/[^/]+\/(details|assignment|transition)$/.test(pathname)) { if (input.expected_version !== program.version) fail(409, "version_conflict", "The Program changed before this update was recorded."); const parts = pathname.split("/"), id = decodeURIComponent(parts.at(-2) || ""), command = parts.at(-1), item = detail.control_implementations.find((value) => value.id === id); if (!item) fail(404, "control_implementation_not_found", "The selected safeguard is no longer available."); if (item.version !== input.expected_implementation_version) fail(409, "version_conflict", "The safeguard changed before this update was recorded."); if (command === "details") Object.assign(item, pick(input, ["name", "description", "implementation_type", "scope", "effective_from"])); if (command === "assignment") item.owner_principal_id = input.owner_principal_id; if (command === "transition") { if (!targets("safeguard", item.status).includes(input.to)) fail(409, "transition_invalid", `The safeguard cannot move from ${item.status} to ${input.to}.`); item.status = input.to; } item.version += 1; return finish(); }
    if (/\/api\/v1\/programs\/[^/]+\/evidence-contracts\/[^/]+\/(revision|transition)$/.test(pathname)) { if (input.expected_version !== program.version) fail(409, "version_conflict", "The Program changed before this update was recorded."); const parts = pathname.split("/"), id = decodeURIComponent(parts.at(-2) || ""), command = parts.at(-1), prior = detail.evidence_contracts.find((value) => value.id === id); if (!prior) fail(404, "evidence_contract_not_found", "The selected evidence check is no longer available."); if (prior.version !== input.expected_contract_version) fail(409, "version_conflict", "The evidence check changed before this update was recorded."); if (command === "revision") Object.assign(prior, pick(input, ["name", "claim", "acceptable_source_ids", "population_scope", "freshness_minutes", "minimum_coverage", "independence_required", "contradiction_policy", "failure_action"]), { status: prior.status === "ACTIVE" ? "DRAFT" : prior.status, version: prior.version + 1, configured_by: actor.id }); else { const allowed = prior.status === "ACTIVE" ? ["RETIRED"] : prior.status === "DRAFT" ? prior.configured_by === actor.id ? ["RETIRED"] : ["ACTIVE", "RETIRED"] : []; if (!allowed.includes(input.to)) { const makerChecker = prior.status === "DRAFT" && input.to === "ACTIVE" && prior.configured_by === actor.id; fail(409, makerChecker ? "maker_checker_required" : "transition_invalid", makerChecker ? "A different reviewer must activate this evidence check." : `The evidence check cannot move from ${prior.status} to ${input.to}.`); } prior.status = input.to; prior.version += 1; } return finish(); }
    if (/\/api\/v1\/programs\/[^/]+\/evidence-contracts\/[^/]+\/assessments$/.test(pathname)) { if (input.expected_version !== program.version) fail(409, "version_conflict", "The Program changed before this update was recorded."); const id = decodeURIComponent(pathname.split("/").at(-2) || ""); if (input.contract_id !== id) fail(400, "contract_mismatch", "The evidence check in the request does not match the selected check."); detail.evidence_assessments.push({ id: `assessment-${detail.evidence_assessments.length + 1}`, ...input, contract_id: id, assessed_at: input.assessed_at, valid_until: input.valid_until, assessed_by: actor.id }); return finish(); }
    return { handled: false };
  }

  function reviewDigest({ programID, program, summary, acknowledged, now }) {
    if (programID !== "program-ndpa") return { program_id: programID, state: "NO_BASELINE", review_required: true, checkpoint: null, current_program_version: program.version, current_projection_version: 0, current_overall: "UNKNOWN", baseline_overall: "UNKNOWN", open_matter_count: 0, open_matter_delta: 0, changes: [], changes_total: 0, changes_omitted: 0, current_exceptions: [], current_exceptions_total: 0, new_exceptions: [], new_exceptions_total: 0, resolved_exceptions: [], resolved_exceptions_total: 0 };
    const checkpoint = { id: "review-ndpa-1", tenant_id: "bank-demo", program_id: programID, principal_id: "role-cro", program_version: acknowledged ? program.version : 10, projection_version: acknowledged ? 3 : 2, accepted_at: acknowledged ? now : "2026-08-04T09:00:00Z" };
    if (acknowledged) return { program_id: programID, state: "CURRENT", review_required: false, checkpoint, current_program_version: program.version, current_projection_version: 3, current_overall: "EVIDENCE_INSUFFICIENT", baseline_overall: "EVIDENCE_INSUFFICIENT", open_matter_count: 2, open_matter_delta: 0, changes: [], changes_total: 0, changes_omitted: 0, current_exceptions: summary.reasons, current_exceptions_total: 1, new_exceptions: [], new_exceptions_total: 0, resolved_exceptions: [], resolved_exceptions_total: 0 };
    const changes = [{ kind: "STATE", summary: "Overall status changed from current to evidence insufficient." }, { kind: "EVIDENCE", summary: "Evidence for Annual return evidence package was assessed as partially supported.", object_type: "EVIDENCE_CONTRACT", object_id: "contract-return" }, { kind: "CHANGE", summary: "Observed change: requirement changed.", object_type: "REQUIREMENT", object_id: "req-2" }];
    return { program_id: programID, state: "CHANGED", review_required: true, checkpoint, current_program_version: program.version, current_projection_version: 3, current_overall: "EVIDENCE_INSUFFICIENT", baseline_overall: "CURRENT", open_matter_count: 2, open_matter_delta: 2, changes, changes_total: 3, changes_omitted: 0, current_exceptions: summary.reasons, current_exceptions_total: 1, new_exceptions: summary.reasons, new_exceptions_total: 1, resolved_exceptions: [], resolved_exceptions_total: 0 };
  }

  function connectedDataRequest({ pathname, method, url, input, state, ErrorType, now }) {
    const { sources, connections, views, bindings } = state;
    const fail = (status, code, message) => { throw new ErrorType(status, code, message); };
    if (pathname === "/api/v1/evidence/sources" && method === "GET") return { handled: true, body: { items: [{ id: "source-ndpc", tenant_id: "bank-demo", legal_entity_id: "bank-ng", code: "NDPC-PUBLICATIONS", name: "NDPC official publications", type: "REGULATORY", authority_class: "AUTHORITATIVE", expected_freshness_minutes: 1440, last_observed_at: now, last_success_at: now, health: "CURRENT", status: "ACTIVE", version: 3 }, { id: "source-iam", tenant_id: "bank-demo", legal_entity_id: "bank-ng", code: "IAM-ENTITLEMENTS", name: "Identity and access records", type: "SYSTEM", authority_class: "SYSTEM_OF_RECORD", expected_freshness_minutes: 60, last_observed_at: now, last_success_at: "2026-08-06T14:30:00Z", health: "DEGRADED", status: "ACTIVE", version: 8 }, ...sources] } };
    if (pathname === "/api/v1/evidence/sources" && method === "POST") { const source = { id: `source-${sources.length + 1}`, tenant_id: "bank-demo", ...input, health: "UNKNOWN", status: "ACTIVE", version: 1, created_at: now, updated_at: now }; sources.push(source); return { handled: true, body: source }; }
    if (/\/api\/v1\/config\/sources\/[^/]+\/connections$/.test(pathname) && method === "POST") { const sourceID = decodeURIComponent(pathname.split("/").at(-2) || ""); if (!sources.some((item) => item.id === sourceID)) fail(404, "source_not_found", "The selected connected-data source is no longer available."); const connection = { connection_id: `connection-${connections.length + 1}`, source_id: sourceID, ...input, status: "ACTIVE", version: 1 }; connections.push(connection); return { handled: true, body: connection }; }
    if (/\/api\/v1\/config\/source-connections\/[^/]+\/views$/.test(pathname) && method === "POST") { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), connection = connections.find((item) => item.connection_id === id); if (!connection || input.connection_version !== connection.version) fail(409, "version_conflict", "The source connection changed before its view was created."); const view = { view_id: `view-${views.length + 1}`, connection_id: id, connection_version: connection.version, source_id: connection.source_id, ...input, native_schema: [], version: 1 }; views.push(view); return { handled: true, body: view }; }
    if (/\/api\/v1\/config\/source-views\/[^/]+\/inspect$/.test(pathname) && method === "POST") { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), view = views.find((item) => item.view_id === id); if (!view || view.version !== Number(url.searchParams.get("version"))) fail(409, "version_conflict", "The source view changed before its fields were inspected."); Object.assign(view, { native_schema: [{ name: "status", native_type: "string", nullable: false }, { name: "current", native_type: "boolean", nullable: false }], schema_fingerprint: `schema-${view.version}`, version: view.version + 1 }); return { handled: true, body: { view } }; }
    if (/\/api\/v1\/config\/source-views\/[^/]+\/bindings$/.test(pathname) && method === "POST") { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), view = views.find((item) => item.view_id === id); if (!view || view.version !== input.view_version) fail(409, "version_conflict", "The source view changed before its monitoring binding was created."); const binding = { binding_id: `binding-${bindings.length + 1}`, view_id: id, view_version: view.version, source_id: view.source_id, ...input, status: "ACTIVE", version: 1 }; bindings.push(binding); return { handled: true, body: binding }; }
    return { handled: false };
  }

  function monitoringRequest({ pathname, method, input, programID, forms, checks, results, actor, evidenceRequest, evidenceRequests, monitoringResult, ErrorType, now }) {
    const fail = (status, code, message) => { throw new ErrorType(status, code, message); };
    if (pathname === `/api/v1/programs/${programID}/form-templates` && method === "GET") return { handled: true, body: { items: forms.filter((item) => item.program_id === programID) } };
    if (pathname === `/api/v1/programs/${programID}/form-templates` && method === "POST") { const form = { id: `form-${forms.length + 1}`, tenant_id: "bank-demo", program_id: programID, ...input, status: "DRAFT", created_by: actor.id, version: 1, created_at: now, updated_at: now }; forms.push(form); return { handled: true, body: form }; }
    if (/\/api\/v1\/programs\/[^/]+\/form-templates\/[^/]+\/transition$/.test(pathname) && method === "POST") { const id = pathname.split("/").at(-2), prior = forms.find((item) => item.id === id); if (!prior || prior.version !== input.expected_version) fail(409, "version_conflict", "The form changed before its status was updated."); if (!targets("monitoring", prior.status).includes(input.to)) fail(409, "transition_invalid", `The form cannot move from ${prior.status} to ${input.to}.`); if (input.to === "ACTIVE" && prior.submitted_by === actor.id) fail(409, "maker_checker_required", "A different reviewer must approve this form."); const updated = { ...prior, status: input.to, submitted_by: input.to === "PENDING_APPROVAL" ? actor.id : prior.submitted_by, approved_by: input.to === "ACTIVE" ? actor.id : prior.approved_by, version: prior.version + 1, updated_at: now }; forms.splice(forms.indexOf(prior), 1, updated); return { handled: true, body: updated }; }
    if (/\/api\/v1\/programs\/[^/]+\/form-templates\/[^/]+\/collections$/.test(pathname) && method === "POST") { const formID = decodeURIComponent(pathname.split("/").at(-2) || ""), form = forms.find((item) => item.id === formID); if (!form) fail(404, "form_template_not_found", "The selected collection form is no longer available."); if (form.version !== input.form_template_version) fail(409, "version_conflict", "The collection form changed before this request was created."); const request = { ...structuredClone(evidenceRequest), id: `evidence-monitoring-${form.id}-${evidenceRequests.length}`, subject_type: "PROGRAM", subject_id: programID, title: form.name, purpose: form.purpose, why_you: "You are assigned to complete this Program monitoring collection.", status: "READY", deadline: input.deadline, known_facts: { period_start: input.period_start, period_end: input.period_end, form_template_id: form.id, form_template_version: form.version }, fields: structuredClone(form.fields || []), recipient: { type: "INTERNAL_PRINCIPAL", state: "ASSIGNED", principal_id: "role-privacy-control", display_name: "Privacy Control Owner" }, version: 1, created_at: now, updated_at: now }; evidenceRequests.push(request); return { handled: true, body: request }; }
    if (pathname === `/api/v1/programs/${programID}/monitoring-checks` && method === "GET") return { handled: true, body: { items: checks.filter((item) => item.program_id === programID) } };
    if (pathname === `/api/v1/programs/${programID}/monitoring-checks` && method === "POST") { const check = { id: `monitor-${checks.length + 1}`, tenant_id: "bank-demo", program_id: programID, ...input, status: "DRAFT", is_current: true, created_by: actor.id, version: 1, created_at: now, updated_at: now }; checks.push(check); return { handled: true, body: check }; }
    if (/\/api\/v1\/monitoring-checks\/[^/]+\/transition$/.test(pathname) && method === "POST") { const id = pathname.split("/").at(-2), prior = checks.find((item) => item.id === id); if (!prior || prior.version !== input.expected_version) fail(409, "version_conflict", "The monitoring check changed before its status was updated."); if (!targets("monitoring", prior.status).includes(input.to)) fail(409, "transition_invalid", `The monitoring check cannot move from ${prior.status} to ${input.to}.`); if (input.to === "ACTIVE" && prior.submitted_by === actor.id) fail(409, "maker_checker_required", "A different reviewer must approve this monitoring check."); const updated = { ...prior, status: input.to, submitted_by: input.to === "PENDING_APPROVAL" ? actor.id : prior.submitted_by, approved_by: input.to === "ACTIVE" ? actor.id : prior.approved_by, version: prior.version + 1, updated_at: now }; checks.splice(checks.indexOf(prior), 1, updated); return { handled: true, body: updated }; }
    if (/\/api\/v1\/monitoring-checks\/[^/]+\/results$/.test(pathname) && method === "GET") { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), result = results.get(id); return { handled: true, body: { items: result ? [result] : [] } }; }
    if (/\/api\/v1\/monitoring-checks\/[^/]+\/evaluate-source$/.test(pathname) && method === "POST") { const id = decodeURIComponent(pathname.split("/").at(-2) || ""), check = checks.find((item) => item.id === id); if (!check) fail(404, "monitoring_check_not_found", "The selected monitoring check is no longer available."); if (check.version !== input.check_version) fail(409, "version_conflict", "The monitoring check changed before it was evaluated."); const rules = check.source_rules || [], ruleResults = rules.map((rule) => ({ rule_id: rule.id, field_id: rule.field, outcome: "FAIL", reason: `The sample source has no value confirming ${rule.field} equals ${String(rule.expected)}.` })); const result = { id: `result-${id}-${check.version}`, monitoring_check_id: id, monitoring_check_version: check.version, evaluated_at: now, evaluation: { score: rules.reduce((total, rule) => total + Number(rule.risk_points || 0), 0), band: rules.length ? "CRITICAL" : "UNKNOWN", coverage: rules.length ? 1 : 0, rule_results: ruleResults } }; results.set(id, result); return { handled: true, body: result }; }
    return { handled: false };
  }

  global.ClearSightStaticWorkflowRuntime = { accounts, authRequest, targets, pick, outcomeFields, principal, changeMatterContext, finishMatterMutation, matterOperations, matterMutationRequest, programOperations, programResourceRequest, reviewDigest, connectedDataRequest, monitoringRequest };
})(globalThis);
