export type InterventionClass = "REVIEW" | "DECISION" | "AUTHORIZATION" | "EVIDENCE_EXCEPTION" | "ESCALATION" | "VERIFICATION" | "EXTERNAL_REPRESENTATION";
export type SourceReference = { id?: string; label: string; version?: string; observed_at?: string };
export type VerificationPlan = { state?: string; expected_outcome?: string; method?: string; next_check_at?: string };
export type WorkReceipt = { actor_kind: "DETERMINISTIC" | "AI_OPERATOR" | string; actor_id: string; actor_version?: string; autonomy_level: "OBSERVE" | "ANALYZE" | "PREPARE" | "EXECUTE_REVERSIBLE" | string; summary: string; sources?: SourceReference[]; completed?: string[]; blocked?: string[]; generated_at?: string; audit_reference?: string };
export type GovernedRecommendation = { proposed_action: string; rationale?: string; alternatives?: string[]; required_authority?: string; expected_next_state?: string; reversible?: boolean; sources?: SourceReference[]; assumptions?: string[]; contradictions?: string[]; verification?: VerificationPlan };
export type AuthorityContext = { responsibility: string; decision_type?: string; materiality: number };
export type AttentionItem = { id: string; type: string; title: string; why_now: string; scope: string; state: string; evidence: string; owner: string; due_at: string; primary_action: string; action_target_type?: "PROGRAM" | "MATTER" | "EVIDENCE_REQUEST"; action_target_id?: string; intervention_class?: InterventionClass; material_conclusion?: string; change_summary?: string; authority?: AuthorityContext; recommendation?: GovernedRecommendation; prepared_work?: WorkReceipt; verification?: VerificationPlan; };
export type InterventionSummary = AttentionItem;
export type SourceScalar = { kind: "NULL" | "STRING" | "NUMBER" | "BOOL" | "TIME" | string; text?: string };
export type BindingReference = { binding_id: string; binding_version: number };
export type SourceOperationReceipt = { source_id: string; binding_id?: string; binding_version?: string; adapter_kind?: string; adapter_version?: string; observed_at: string; count: number; completeness: "COMPLETE" | "PARTIAL" | "UNKNOWN" | string; schema_fingerprint?: string; artifact_id?: string; artifact_sha256?: string; parser_version?: string };
export type SourceResolution = BindingReference & { mode: "PREFILL" | "OPTIONS" | "VALIDATE" | "EVIDENCE" | string; binding_name: string; source_id: string; state: "CURRENT" | "PARTIAL" | "STALE" | "NOT_FOUND" | "AMBIGUOUS" | "SCHEMA_DRIFT" | "UNAVAILABLE" | "INVALID" | string; value?: SourceScalar; records?: Array<Record<string, SourceScalar>>; receipt?: SourceOperationReceipt; failure_code?: string };
export type FieldBindingReference = BindingReference & { mode: "PREFILL" | "OPTIONS" | "VALIDATE" | "EVIDENCE" | string; value_field?: string; lookup_value?: { source: "SUBJECT_ID" | "KNOWN_FACT" | string; key?: string } };
export type RequestBindingReference = BindingReference & { lookup_value: { source: "SUBJECT_ID" | "KNOWN_FACT" | string; key?: string }; resolution?: SourceResolution };
export type CapturePresentationMode = "CLASSIC" | "WIZARD" | "AUTOMATIC";
export type CaptureConditionOperator = "EQUALS" | "NOT_EQUALS" | "IN" | "NOT_IN" | "ANSWERED";
export type CaptureFieldType = "short_text" | "long_text" | "email" | "telephone" | "url" | "integer" | "decimal" | "percentage" | "currency" | "date" | "yes_no" | "single_select" | "multi_select" | "checkbox" | "attestation" | "file" | "photo" | "signature" | "vendor_document" | "text" | "number";
export type CapturePresentation = { default_mode: CapturePresentationMode; allow_mode_switch: boolean };
export type CaptureVisibilityCondition = { field_id: string; operator: CaptureConditionOperator; values?: string[] };
export type CaptureSection = { id: string; title: string; help?: string; condition?: CaptureVisibilityCondition };
export type CaptureFieldConstraints = {
  min_length?: number;
  max_length?: number;
  minimum?: number;
  maximum?: number;
  step?: number;
  decimal_precision?: number;
  currency?: string;
  min_date?: string;
  max_date?: string;
  min_selections?: number;
  max_selections?: number;
  max_files?: number;
  max_file_bytes?: number;
};
export type CaptureDocumentAnswer = { artifact_id: string; document_type: string; reference?: string; issued_by?: string; issued_on?: string; expires_on?: string };
export type CaptureAnswerValue = { text?: string; values?: string[]; artifact_ids?: string[]; document?: CaptureDocumentAnswer };
export type CaptureAnswers = Record<string, CaptureAnswerValue>;
export type LegacyCaptureAnswers = Record<string, string>;
export type CaptureAnswerInputs = Record<string, CaptureAnswerValue | string>;
export type CaptureField = {
  id: string;
  section_id?: string;
  label: string;
  type: CaptureFieldType | string;
  required: boolean;
  description?: string;
  options?: string[];
  accepted_formats?: string[];
  attestation?: string;
  constraints?: CaptureFieldConstraints;
  condition?: CaptureVisibilityCondition;
  bindings?: FieldBindingReference[];
  source_resolutions?: SourceResolution[];
};
export type CaptureFormContract = { presentation: CapturePresentation; sections: CaptureSection[]; fields: CaptureField[] };
export type CaptureDraft = { answers: CaptureAnswers; presentation_mode: CapturePresentationMode; version: number };
export type EvidenceRecipient = { type?: "INTERNAL_PRINCIPAL" | "EXTERNAL_AUDIENCE"; principal_id?: string; audience_hint?: string; state?: "ASSIGNED" | "REASSIGNMENT_REQUIRED" | "LEGACY_UNASSIGNED"; revision?: number; issue_reason?: string };
export type CaptureRequest = { id: string; title: string; purpose: string; why_you: string; status: string; sensitivity: string; audience_type?: string; recipient?: EvidenceRecipient; created_by?: string; estimated_minutes: number; deadline: string; known_facts: Record<string, string>; presentation?: CapturePresentation; sections?: CaptureSection[]; fields: CaptureField[]; version: number; };
export type AuthorityPrincipal = { id: string; display_name: string; kind: string; role: string };
export type AuthorityResolution = { principal: AuthorityPrincipal; candidate_principals?: AuthorityPrincipal[]; strategy?: string; rule_id: string; policy_version: string; explanation: string; };
export type IntegrityFinding = { type: string; severity: string; summary: string; required_action: string; rule_ids?: string[]; };
export type PolicySummary = { id: string; code: string; name: string; status: string; version: number; effective_from?: string; };
export type AutomationPolicy = { id: string; tenant_id: string; code: string; name: string; action_class: string; eligibility: Record<string, unknown>; blast_radius_limit: Record<string, unknown>; verification_contract: Record<string, unknown>; status: string; effective_from?: string; effective_until?: string; version: number; };
export type Drift = { id: string; subject_type: string; subject_id: string; dimension: string; severity: number; summary: string; required_action: string; detected_at: string; };
export type Readiness = { tenant_id: string; status: string; baseline_known: boolean; generated_at: string; dimensions: { current: number; aging: number; at_risk: number; unknown: number; blocked_routing: number; pending_human: number; }; active_drifts: Drift[]; recommended_actions: string[]; };
export type GuideSurface = "TODAY" | "VENDORS";
export type GuideStep = { id: string; title: string; description: string; action?: string; view?: "today" | "programs" | "work" | "imports" | "explore" | "configure" | "vendors"; target?: string; intent?: string; optional?: boolean };
export type OnboardingGuide = { code: string; surface?: GuideSurface; profile?: string; role: string; role_codes?: string[]; priority?: number; version: number; title: string; description: string; illustration: string; steps: GuideStep[] };
export type OnboardingState = { tenant_id: string; principal_id: string; guide_code: string; guide_version: number; current_step: number; completed: boolean; dismissed: boolean; updated_at?: string; version: number };
export type WorkflowTask = { id: string; tenant_id: string; workflow_id: string; step_key: string; responsibility: string; principal_id?: string; title: string; status: string; due_at?: string; claimed_at?: string; completed_at?: string; context?: Record<string, string>; source_bindings?: BindingReference[]; version: number; };
export type EvidenceSource = { id: string; tenant_id: string; legal_entity_id?: string; code: string; name: string; type: string; authority_class: string; owner_principal_id?: string; expected_freshness_minutes: number; last_observed_at?: string; last_success_at?: string; health: string; status: string; version: number; };
export type EvidenceField = CaptureField;
export type EvidenceRequest = { id: string; tenant_id: string; subject_type: string; subject_id: string; title: string; purpose: string; why_you: string; sensitivity: string; audience_type: string; recipient?: EvidenceRecipient; created_by?: string; estimated_minutes: number; deadline: string; known_facts: Record<string, string>; fields: EvidenceField[]; source_bindings?: RequestBindingReference[]; status: string; version: number; created_at: string; updated_at: string; };

export type ProgramState = "CURRENT" | "AT_RISK" | "GAP_IDENTIFIED" | "EVIDENCE_INSUFFICIENT" | "IMPLEMENTATION_PENDING" | "OVERDUE" | "UNDER_REVIEW" | "NOT_APPLICABLE" | "UNKNOWN";
export type Program = { id: string; tenant_id: string; legal_entity_id?: string; code: string; name: string; type: string; status: string; owning_function: string; owner_principal_id?: string; authority_principal_id?: string; jurisdiction?: string; scope: Record<string, unknown>; effective_from: string; effective_until?: string; created_at: string; updated_at: string; version: number; };
export type Requirement = { id: string; code: string; title: string; statement: string; status: string; source_anchor?: string; };
export type ControlImplementation = { id: string; name: string; description: string; implementation_type: string; status: string; };
export type EvidenceContract = { id: string; code: string; name: string; claim: string; status: string; freshness_minutes: number; minimum_coverage: number; };
export type StateReason = { code: string; summary: string; object_type?: string; object_id?: string; };
export type ProgramStateSnapshot = { id: string; overall_state?: ProgramState; overall?: ProgramState; dimensions: Record<string, ProgramState>; reasons: StateReason[]; open_matter_count: number; trigger_type?: string; trigger_id?: string; generated_at: string; program_version: number; projection_version: number; };
export type ProgramAggregate = { state_label: string; program: Program; requirements: Requirement[]; applicability: Array<{ id: string; requirement_id: string; status: string; rationale: string }>; control_objectives: Array<{ id: string; code: string; name: string; outcome: string; status: string }>; control_implementations: ControlImplementation[]; requirement_control_links: Array<{ requirement_id: string; implementation_id: string }>; evidence_contracts: EvidenceContract[]; evidence_assessments: Array<{ id: string; contract_id: string; conclusion: string; coverage: number; assessed_at: string; valid_until?: string }>; current_state?: ProgramStateSnapshot; triggers: Array<{ id: string; type: string; observed_at: string; source: string }>; };

export type Matter = { id: string; tenant_id: string; reference: string; type: string; status: string; priority: number; title: string; summary: string; scope: Record<string, unknown>; known_facts: Record<string, unknown>; missing_facts: unknown[]; contradictions: unknown[]; owner_principal_id?: string; required_authority?: string; due_at?: string; closed_at?: string; closure_reason?: string; created_at: string; updated_at: string; version: number; };
export type MatterAction = { id: string; title: string; description: string; status: string; due_at?: string; implemented_at?: string; };
export type MatterDecision = { id: string; type: string; status: string; selected_option?: string; rationale: string; decided_at?: string; };
export type VerificationContract = { id: string; expected_outcome: string; status: string; observation_period_minutes: number; };
export type VerificationResult = { id: string; contract_id: string; result: string; rationale: string; observed_at: string; };
export type ResponsePackage = { id: string; purpose: string; audience: string; status: string; transmitted_at?: string; acknowledged_at?: string; };
export type MatterAggregate = { type_label: string; status_label: string; next_action: string; matter: Matter; links: Array<{ id: string; program_id?: string; requirement_id?: string; control_id?: string; relationship: string }>; decisions: MatterDecision[]; actions: MatterAction[]; verification_contracts: VerificationContract[]; verification_results: VerificationResult[]; response_packages: ResponsePackage[]; closure: { ready: boolean; reasons: string[] }; };
