import { useEffect, useState } from "react";
import { loadEmployeeActivity, loadEmployeeProfile, loadEmployeeWork, type EmployeeActivityItem, type EmployeeProfile, type EmployeeWorkItem } from "../api";
import { apiErrorKind } from "../http";

export function EmployeeProfileWorkspace({ personID, onOpenMatter }: { personID?: string; onOpenMatter: (id: string) => void }) {
  const [profile, setProfile] = useState<EmployeeProfile>();
  const [work, setWork] = useState<EmployeeWorkItem[]>([]);
  const [activity, setActivity] = useState<EmployeeActivityItem[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "not-found" | "unavailable">("loading");
  useEffect(() => { let active = true; if (!personID) { setState("not-found"); return; } setState("loading"); Promise.all([loadEmployeeProfile(personID), loadEmployeeWork(personID), loadEmployeeActivity(personID)]).then(([nextProfile,nextWork,nextActivity]) => { if (!active) return; setProfile(nextProfile); setWork(nextWork.items); setActivity(nextActivity.items); setState("ready"); }).catch((error) => { if (active) setState(apiErrorKind(error) === "not_found" ? "not-found" : "unavailable"); }); return () => { active = false; }; }, [personID]);
  if (state === "loading") return <div className="workspace-loading" aria-live="polite">Loading employee record…</div>;
  if (state === "not-found") return <section className="employee-profile-empty"><h1>Employee record unavailable</h1><p>The employee record is not available for your role or legal entity.</p></section>;
  if (state === "unavailable" || !profile) return <section className="employee-profile-empty"><h1>Employee record unavailable</h1><p>Retry after the employee and assignment records are available.</p></section>;
  const metric = (key: string) => profile.metrics[key]?.value ?? 0;
  return <section className="employee-profile"><header className="employee-profile-hero"><div><span className="eyebrow">Employee record</span><h1>{profile.person.display_name}</h1><p>{[profile.person.position, profile.person.function].filter(Boolean).join(" · ") || "Position not recorded"}</p></div><span className="employee-profile-status">{profile.person.status}</span></header><div className="employee-metrics"><Metric label="Open assignments" value={metric("active")}/><Metric label="Overdue" value={metric("overdue")} tone={metric("overdue") > 0 ? "risk" : undefined}/><Metric label="Blocked" value={metric("blocked")} tone={metric("blocked") > 0 ? "risk" : undefined}/><Metric label="Outcome checks" value={metric("awaiting_outcome")}/></div><div className="employee-columns"><section className="employee-card"><div className="employee-card-heading"><div><span className="eyebrow">Current work</span><h2>Assignments</h2></div></div>{work.length ? <ul className="employee-list">{work.map((item) => <li key={item.id}><button type="button" onClick={() => onOpenMatter(item.record_id)}><strong>{item.title}</strong><span>{item.responsibility.replaceAll("_", " ")} · {item.status.replaceAll("_", " ")}</span></button>{item.due_at && <time dateTime={item.due_at}>Due {new Date(item.due_at).toLocaleDateString()}</time>}</li>)}</ul> : <p className="employee-empty">No current assignments are recorded.</p>}</section><section className="employee-card"><div className="employee-card-heading"><div><span className="eyebrow">Recorded activity</span><h2>Audit trail</h2></div></div>{activity.length ? <ol className="employee-timeline">{activity.map((item) => <li key={item.event_id}><button type="button" onClick={() => onOpenMatter(item.record_id)}><strong>{item.action.replaceAll("_", " ")}</strong><span>{item.title}</span></button><time dateTime={item.occurred_at}>{new Date(item.occurred_at).toLocaleString()}</time></li>)}</ol> : <p className="employee-empty">No recorded activity is available for the selected scope.</p>}</section></div></section>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone?: "risk" }) { return <div className={`employee-metric${tone ? ` ${tone}` : ""}`}><span>{label}</span><strong>{value}</strong></div>; }
